# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codefly < Formula
  desc "codefly CLI"
  homepage "https://codefly.ai"
  version "0.0.1"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/codefly-dev/cli-releases/releases/download/v0.0.1/codefly-darwin-amd64"
      sha256 "e1be9d7e6fff12c50aecb4f96249b3406c8aabe903c1f393807bff7661b46fd2"
    end
    if Hardware::CPU.intel?
      url  "https://github.com/codefly-dev/cli-releases/releases/download/v0.0.1/codefly-darwin-amd64"
    end

    def install
      bin.install "codefly"
    end
  end

  def caveats
    <<~EOS
      How to use your tool after installation
    EOS
  end

  test do
    codefly version
  end
end
