# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codefly < Formula
  desc "codefly CLI"
  homepage "https://codefly.ai"
  version "0.0.1"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/codefly-dev/cli-releases/releases/download/v0.0.1/codefly-darwin-amd64"

      def install
        bin.install "codefly init"
      end
    end
    if Hardware::CPU.intel?
      url  "https://github.com/codefly-dev/cli-releases/releases/download/v0.0.1/codefly-darwin-amd64"

      def install
        bin.install "codefly init"
      end
    end
  end

  def caveats
    <<~EOS
      How to use your tool after installation
    EOS
  end

  test do
    codefly version
  end
end
