# This file was generated by GoReleaser. DO NOT EDIT.
cask "codefly" do
  version "0.1.80"

  on_macos do
    on_intel do
      sha256 "71dd639ac47cf92ee839cfa83901d1ca71400916af23fcd587ae297e16116dc6"
      url "https://github.com/codefly-dev/cli/releases/download/v#{version}/codefly_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/codefly-dev/cli/"
    end
    on_arm do
      sha256 "0d338a9d498a189380a1c5fa5f4ab2eb821f02b62504c208b8bb29f633a953a5"
      url "https://github.com/codefly-dev/cli/releases/download/v#{version}/codefly_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/codefly-dev/cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "54f01e84c4858f6370dfa48645268337d5ff54d432c90323f95c0e0c5536f900"
      url "https://github.com/codefly-dev/cli/releases/download/v#{version}/codefly_#{version}_linux_amd64.tar.gz",
        verified: "github.com/codefly-dev/cli/"
    end
    on_arm do
      sha256 "803a263dd692ca9c9a1aec15e1a04e796237bc8140cf196ac274d7161fc4f78b"
      url "https://github.com/codefly-dev/cli/releases/download/v#{version}/codefly_#{version}_linux_arm64.tar.gz",
        verified: "github.com/codefly-dev/cli/"
    end
  end

  name "codefly"
  desc "Build, run, test, and deploy services in a Codefly workspace"
  homepage "https://codefly.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codefly"

  # No zap stanza required

end
