# This file was generated by GoReleaser. DO NOT EDIT.
cask "codefly" do
  version "0.1.98"

  on_macos do
    on_intel do
      sha256 "8716428f334902bed8b6586ea59dcc9ec525c2427fa814c3959f79631445bf4b"
      url "https://github.com/codefly-dev/cli/releases/download/v#{version}/codefly_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/codefly-dev/cli/"
    end
    on_arm do
      sha256 "ed343f76fc405d9d023b2bc4be9cb77283eaf46c2139b58effe3d6c7080bd503"
      url "https://github.com/codefly-dev/cli/releases/download/v#{version}/codefly_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/codefly-dev/cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "0a626fb22fe7a17cf3c7aaa498a58bcb891f6be054a7b897053a0c12c96c7448"
      url "https://github.com/codefly-dev/cli/releases/download/v#{version}/codefly_#{version}_linux_amd64.tar.gz",
        verified: "github.com/codefly-dev/cli/"
    end
    on_arm do
      sha256 "89de63531a141ae8faddd5d2d4d1f7ed16a2aa8e50959036cbc8cb6f847f3e6a"
      url "https://github.com/codefly-dev/cli/releases/download/v#{version}/codefly_#{version}_linux_arm64.tar.gz",
        verified: "github.com/codefly-dev/cli/"
    end
  end

  name "codefly"
  desc "Build, run, test, and deploy services in a Codefly workspace"
  homepage "https://codefly.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codefly"

  # No zap stanza required

end
