# This file was generated by GoReleaser. DO NOT EDIT.
cask "codefly" do
  version "0.1.139"

  on_macos do
    on_intel do
      sha256 "d7c50e5d09cae7d550ef30a2f376a0be3cd210f42d9b65a02dd7794d0fa7ece7"
      url "https://github.com/codefly-dev/cli/releases/download/v#{version}/codefly_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/codefly-dev/cli/"
    end
    on_arm do
      sha256 "231e3533f3dfa1ee206d8ddf0bcbfe2dadcbcb21b6f384a28c9a08589bba6351"
      url "https://github.com/codefly-dev/cli/releases/download/v#{version}/codefly_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/codefly-dev/cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "df2f2523efbfa2bb0fdb813c5d427693978be57a04e3a66f907404e44c58bbc5"
      url "https://github.com/codefly-dev/cli/releases/download/v#{version}/codefly_#{version}_linux_amd64.tar.gz",
        verified: "github.com/codefly-dev/cli/"
    end
    on_arm do
      sha256 "0535676021cc15d0f7412cc35f433a7bbd9e47b8f50461f27f2a9159cb8890fb"
      url "https://github.com/codefly-dev/cli/releases/download/v#{version}/codefly_#{version}_linux_arm64.tar.gz",
        verified: "github.com/codefly-dev/cli/"
    end
  end

  name "codefly"
  desc "Build, run, test, and deploy services in a Codefly workspace"
  homepage "https://codefly.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codefly"

  # No zap stanza required

end
