name: Homebrew Formula Test

on: [push, pull_request]

jobs:
  test:
    runs-on: macOS-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Create Test Tap
        run: |
          brew tap-new codefly-dev/ci
          cp codefly.rb "$(brew --repository codefly-dev/ci)/Formula/codefly.rb"

      - name: Test Formula
        run: |
          brew install --build-from-source --verbose codefly-dev/ci/codefly

      - name: Test Binary
        run: |
          codefly version
